config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: ''

  resources :stationeries
  resources :users, except: [:new, :create, :destroy] do
    member do
      get  :stationeries_history
      get  :borrow_stationery
      post :borrow_stationery
      put  :clear_stationery
    end
  end

  root 'stationeries#index'
end

app/models/stationery.rb
class Stationery < ActiveRecord::Base
  TYPES = %w(CONSUMABLE FIXED)

  TYPES.each do |type|
    define_method "#{type.underscore}?" do
      self.stationery_type == type
    end

    define_singleton_method "#{type.underscore}" do
      type
    end
  end

  default_scope -> { order('name ASC') }
  scope :in_stocks, -> { where('in_stocks > 0') }
  validates :name, presence: true
  validates :code, presence: true, uniqueness: true
  validates :stationery_type, presence: true

  has_many :user_stationeries, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  PENALTY = 5 # USD
  STATUSES = %w(ACTIVE DEACTIVED)

  STATUSES.each do |status|
    define_method "#{status.underscore}?" do
      self.status == status
    end

    define_singleton_method "#{status.underscore}" do
      status
    end
  end

  validates :full_name, presence: true
  validates :email, presence: true
  validates :status, presence: true
  has_many :user_stationeries
  has_many :stationeries, through: :user_stationeries

  def can_borrow?
    overdue_stationeries.size < 1
  end

  def overdue_stationeries
    UserStationery.overdues(self)
  end

  def overdue_penalty
    overdue_stationeries.size * PENALTY
  end
end

app/models/user_stationery.rb
class UserStationery < ActiveRecord::Base
  STATUSES = %w(BORROWED USED CLEARED)

  STATUSES.each do |status|
    define_method "#{status.underscore}?" do
      self.status == status
    end

    define_singleton_method "#{status.underscore}" do
      status
    end
  end

  MAX_BORROW_DAYS = 2.days
  default_scope -> { order('created_at DESC') }
  before_create :set_overdue_at
  before_create :set_used_if_consumable
  belongs_to :user
  belongs_to :stationery

  validates :user, presence: true
  validates :stationery_id, presence: true

  def set_overdue_at
    stationery.in_stocks -=1
    stationery.save
    self.overdue_at = DateTime.now + 2.days if stationery.fixed?
  end

  def set_used_if_consumable
    self.status = UserStationery.used if stationery.consumable?
  end

  def cleared!
    self.status = UserStationery.cleared
    save
  end

  def self.overdues(user)
    joins(:stationery).
      where('overdue_at < ?', Time.now).
      where('stationeries.stationery_type = ?', Stationery.fixed).
      where(user: user, status: UserStationery.borrowed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :current_user_overdue_penalty
  before_filter :current_user_active?
  before_filter :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:full_name, :email, :password, :remember_me) }
  end

  def current_user_overdue_penalty
    if user_signed_in? && current_user.overdue_penalty > 0
      flash.now[:error] = "Please Pay your penalty for not returning the stationeries that you\'ve borowed. Your penalty is USD #{current_user.overdue_penalty}"
    end
  end

  def current_user_active?
    if user_signed_in? && current_user.deactived? && !devise_controller?
      redirect_to destroy_user_session_path
    end
  end
end

app/controllers/stationeries_controller.rb
class StationeriesController < ApplicationController
  before_filter :set_stationery, except: [:index, :new, :create]

  def index
    @stationeries = params[:admin] == '1' ? Stationery.all.page(params[:page]) : Stationery.in_stocks.page(params[:page])
  end

  def new
    @stationery = Stationery.new
  end

  def create
    @stationery = Stationery.new(stationery_params)

    if @stationery.valid? && @stationery.save
      redirect_to stationeries_path(admin: params[:admin]), notice: 'Successfully Added New Stationery.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @stationery.assign_attributes(stationery_params)

    if @stationery.valid? && @stationery.save
      redirect_to stationeries_path(admin: params[:admin]), notice: 'Successfully Updated Stationery.'
    else
      render :edit
    end
  end

  def destroy
    redirect_to stationeries_path(admin: params[:admin]), notice: 'Successfully Deleted Stationery.' if @stationery.destroy
  end

  private

  def stationery_params
    params.require(:stationery).permit(:name, :code, :stationery_type, :in_stocks)
  end

  def set_stationery
    @stationery = Stationery.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, except: [:index]

  def index
    @users = User.all.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    @user.assign_attributes(user_params)

    if @user.valid? && @user.save
      redirect_to users_path(admin: params[:admin]), notice: 'Successfully Updated User detail.'
    else
      render :edit
    end
  end

  def stationeries_history
    @stationeries = @user.user_stationeries.page(params[:page])
  end

  def borrow_stationery
    @user_stationery = @user.user_stationeries.new
    @user_stationery.stationery_id = params[:stationery] if params[:stationery]

    if params[:user_stationery]
      @user_stationery.assign_attributes(user_stationery_params)

      if @user_stationery.valid? && @user_stationery.save
        redirect_to stationeries_path(admin: params[:admin]), notice: 'Successfully Borrowed a Stationery.'
      end
    end
  end

  def clear_stationery
    @stationery = @user.user_stationeries.find params[:stationery]
    @stationery.cleared!
    redirect_to stationeries_path(admin: params[:admin]), notice: 'Borrowed stationery is cleared.'
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :status, :full_name)
  end

  def user_stationery_params
    params.require(:user_stationery).permit(:user_id, :stationery_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stationeries_helper.rb
module StationeriesHelper
  def options_for_stationeries
    Stationery.in_stocks.map{|s| ["#{s.name} - #{s.stationery_type}", s.id]}.unshift(['',''])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Researchbods Stationery
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.application class=controller_name
    = render 'shared/header'
    .container
      = render 'shared/flash'
      = yield

app/views/layouts/dialog.html.slim
doctype html
html
  head
    title Researchbods Stationery
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.dailog class=controller_name
    = yield

app/views/shared/_flash.html.slim
- flash.delete(:timedout).each do |k, v|
  .alert.alert-dismissible class="alert-#{k} mT10" role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close'
      span aria-hidden='true' &times;
    = v

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'Stationeries', stationeries_path(admin: params[:admin])

        - if params[:admin] == '1'
          li
            = link_to 'Users', users_path(admin: params[:admin])
      ul.nav.navbar-nav.pull-right
        li
          = link_to 'Logout', destroy_user_session_path(admin: params[:admin])

app/views/stationeries/_form.html.slim
.row.mT20
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading
        h4 Stationery
      .panel-body
        = simple_form_for(@stationery) do |f|
          = f.error_notification
          = f.input :name
          = f.input :code
          = f.input :in_stocks
          = f.input :stationery_type, collection: Stationery::TYPES, selected: @stationery.stationery_type
          = f.button :submit, 'Save', class: 'btn btn-block btn-default', data: { disable_with: 'Saving...' }
          = link_to 'Cancel', stationeries_path(admin: params[:admin]), class: 'btn btn-block btn-default'

app/views/stationeries/_stationery.html.slim
tr
  td
    = link_to stationery.name.humanize, stationery_path(stationery, admin: params[:admin])
  td
    = stationery.in_stocks
  td
    = stationery.stationery_type
  td
    - if current_user.can_borrow?
      = link_to 'Use / Borrow', borrow_stationery_user_path(current_user, stationery: stationery.id), class: 'btn btn-info btn-sm'
    - if params[:admin] == '1'
      = link_to 'Edit', edit_stationery_path(stationery, admin: params[:admin]), class: 'btn btn-default btn-sm mL10'
      = link_to 'View', stationery_path(stationery, admin: params[:admin]), class: 'btn btn-default mL10 btn-sm'
      = button_to 'Delete', stationery_path(stationery, admin: params[:admin]), method: :delete, class: 'btn btn-danger btn-sm mL10', data: { disable_with: 'Deleting...' }, form: { class: 'display-inline' }

app/views/stationeries/edit.html.slim
= render 'form'

app/views/stationeries/index.html.slim
.row
  .col-sm-12
    - if params[:admin] == '1'
      .pull-left
        = link_to 'New Stationery', new_stationery_path(admin: params[:admin]), class: 'btn btn-default'
    .pull-right
      - if params[:admin] == '1'
        = link_to 'I am not an Admin', stationeries_path(admin: nil), class: 'btn btn-danger'
      - else
        = link_to 'I am Admin', stationeries_path(admin: 1), class: 'btn btn-info'
  .col-sm-12.mT10
    label Stationeries
    table.table.table-bordered
      thead
        tr
          th Name
          th width='200px' Stocks
          th width='100px' TYPE
          th width='350px'
      tbody
        - if @stationeries.empty?
          tr
            td.text-center colspan='4' No Stationeries yet.
        - else
          = render @stationeries
    .mT20.text-center
      = paginate @stationeries

app/views/stationeries/new.html.slim
= render 'form'

app/views/stationeries/show.html.slim
.row.mT20
  .col-sm-8.col-sm-offset-2
    .panel.panel-default
      .panel-heading
        h4 Stationery Detail
      .panel-body
        .row
          .col-sm-3
            label Name:
          .col-sm-9
            p = @stationery.name.humanize
        .row
          .col-sm-3
            label Code:
          .col-sm-9
            p = @stationery.code
        .row
          .col-sm-3
            label In Stocks:
          .col-sm-9
            p = @stationery.in_stocks
        .row
          .col-sm-3
            label Stationery Type:
          .col-sm-9
            p = @stationery.stationery_type
      .panel-footer
        .row
          .col-sm-12
            .pull-left
              - if current_user.can_borrow?
                = link_to 'Use / Borrow Stationery', borrow_stationery_user_path(current_user, stationery: @stationery.id, admin: params[:admin]), class: 'btn btn-info btn-sm'
            .pull-right
              = link_to 'Go back to Stationeries', stationeries_path(admin: params[:admin]), class: 'btn btn-sm btn-default'
              - if params[:admin] == '1'
                = link_to 'Edit', edit_stationery_path(@stationery, admin: params[:admin]), class: 'btn btn-default btn-sm mL10'
                = button_to 'Delete', stationery_path(@stationery, admin: params[:admin]), method: :delete, class: 'btn btn-danger btn-sm mL10', data: { disable_with: 'Deleting...' }, form: { class: 'display-inline' }

app/views/users/_form.html.slim
.row.mT20
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading
        h4 User
      .panel-body
        = simple_form_for(@user) do |f|
          = f.error_notification
          = f.input :full_name
          = f.input :email
          = f.input :status, collection: User::STATUSES, selected: @user.status
          = f.button :submit, 'Save', class: 'btn btn-block btn-default', data: { disable_with: 'Saving...' }
          = link_to 'Cancel', users_path(admin: params[:admin]), class: 'btn btn-block btn-default'

app/views/users/_user.html.slim
tr
  td
    = link_to user.full_name.humanize, user_path(user, admin: params[:admin])
  td
    = user.email
  td
    = user.status
  td
    = link_to 'Edit', edit_user_path(user, admin: params[:admin]), class: 'btn btn-default btn-sm'
    = link_to 'View', user_path(user, admin: params[:admin]), class: 'btn btn-default mL10 btn-sm'

app/views/users/borrow_stationery.html.slim
.row.mT20
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading
        h4 Borrow Stationery
      .panel-body
        = simple_form_for(@user_stationery, url: borrow_stationery_user_path(@user)) do |f|
          = f.error_notification
          = f.hidden_field :user_id
          = f.input :stationery_id, collection: options_for_stationeries, selected: @user_stationery.stationery_id
          = f.button :submit, 'Borrow', class: 'btn btn-block btn-default', data: { disable_with: 'Proccessing...' }
          = link_to 'Cancel', users_path(admin: params[:admin]), class: 'btn btn-block btn-default'

app/views/users/edit.html.slim
= render 'form'

app/views/users/index.html.slim
.row
  .col-sm-12.mT10
    .alert.alert-info
      p
        strong.mR10 NOTE:
        span Assumed that you are an admin and can manage the users to update, deativate or activate user, you can process to borrow them stationery and clear borrowed stationery for the users.
  .col-sm-12.mT10
    label Users
    table.table.table-bordered
      thead
        tr
          th Full Name
          th width='40%' Email
          th width='100px' Status
          th width='230px'
      tbody
        - if @users.empty?
          tr
            td.text-center colspan='4' No Users yet.
        - else
          = render @users
    .mT20.text-center
      = paginate @users

app/views/users/new.html.slim
= render 'form'

app/views/users/show.html.slim
.row.mT20
  .col-sm-10.col-sm-offset-1
    .panel.panel-default
      .panel-heading
        h4 User Detail
      .panel-body
        .row
          .col-sm-2
            label Full Name:
          .col-sm-10
            p = @user.full_name.humanize
        .row
          .col-sm-2
            label Email:
          .col-sm-10
            p = @user.email
        .row
          .col-sm-2
            label Status:
          .col-sm-10
            p = @user.status
        - if @user.overdue_penalty > 0
          .row
            .col-sm-2
              label Overdue Panalty:
            .col-sm-10
              p
                span.mR5 USD
                span = @user.overdue_penalty
      .panel-footer
        .row
          .col-sm-12
            .pull-left
              - if @user.can_borrow?
                = link_to 'Use / Borrow Stationery', borrow_stationery_user_path(@user, admin: params[:admin]), class: 'btn btn-info btn-sm'
              = link_to 'Used / Borrowed Stationery History', stationeries_history_user_path(@user, admin: params[:admin]), class: 'btn btn-default mL10 btn-sm'
            .pull-right
              = link_to 'Go back to Users', users_path(admin: params[:admin]), class: 'btn btn-default btn-sm'
              = link_to 'Edit', edit_user_path(@user, admin: params[:admin]), class: 'btn btn-default mL10 btn-sm'

app/views/users/stationeries_history.html.slim
.row
  .col-sm-12.mT10
    label Stationeries Hsitory
    table.table.table-bordered
      thead
        tr
          th Name
          th width='100px' TYPE
          td width='100px' STATUS
          td width='200px' CREATED
          td width='200px' DUE ON
          th width='200px'
      tbody
        - if @stationeries.empty?
          tr
            td.text-center colspan='3' No Stationeries borrowed yet.
        - else
          - @stationeries.each do |s|
            tr
              td = s.stationery.name
              td = s.stationery.stationery_type
              td = s.status
              td = timeago_tag s.created_at, :nojs => true, :limit => 10.days.ago
              td = s.overdue_at
              td
                - if s.borrowed? && s.stationery.fixed?
                  = button_to 'Clear Borrowed Stationery', clear_stationery_user_path(@user, stationery: s.id, admin: params[:admin]), method: :put, class: 'btn btn-warning btn-sm'
    .mT20.text-center
      = paginate @stationeries